### ISSUE TITLE
关于GList组件嵌套时同时使用自定义遮罩和开启supportStencil时的Bug

### ISSUE THREAD

**Issue by jsion** [fairygui/FairyGUI-unity#105]
GList主容器A，GList副容器B
子Item均使用GoWrapper显示
开启supportStencil，两个容器都用自定义遮罩
B为A的第一个Item，
这两个遮罩在第一个Item位置重叠，然后容器B的遮罩部分就显示透明了
若把B的自定义遮罩改成反向后，遮罩部分能显示，但容器B又无法按页切换了

**Comment by xiaoguzhu** [comment]
首先，正向和反向遮罩是不能嵌套的。如果你说都是正向的，嵌套应该没问题，我看不懂什“显示透明”，“无法按页切换”这些词语表达的意思。所以请使用最新sdk制作一个能重现的demo上传我再看。

**Comment by jsion** [comment]
[GListDemo.zip](https://github.com/fairygui/FairyGUI-unity/files/3539476/GListDemo.zip)
Demo已上传
