### ISSUE TITLE
Chat UI 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#11]
Hi!
i m working on Chat UI thing right now , and stuck itemRenderer width ,

i have seen your Emoji Example , but it is not responsive,

now case is.
1- item renderer's min width should depends upon inner text ,
2- but max width depends upon list available width..

how i can solve.

**Comment by fairygui** [comment]
You case is complicated. Don't use any relations., and just set textfield size and component size in your item renderer. you can get text width by calling GTextField.textWidth.
