### ISSUE TITLE
是否考虑支持lwrp

### ISSUE THREAD

**Issue by mingxxming** [fairygui/FairyGUI-unity#113]

**Comment by xiaoguzhu** [comment]
lwrp不需要特别支持。但关键是lwrp是否支持堆叠相机，因为UI和游戏场景用的不同相机。如果lwrp不出这个功能，那就只能自己修改管线了。

**Comment by mingxxming** [comment]
今天看了很久论坛，看官方说2019.2的版本会支持，还看到设置视频，但是下了2019.3暂时还没看到相机堆叠相关的设置。
