### ISSUE TITLE
富文本组件，文本赋值的时候一个报错

### ISSUE THREAD

**Issue by pl01898759** [fairygui/FairyGUI-unity#115]
谷主你好，我们游戏在使用富文本的时候，出现了一个报错。
首先，我们是在一个列表里面，列表是设置的虚拟列表，列表的ItemRenderer是一个组件，里面只包含了一个富文本，富文本是使用了ubb语法，在某些情况设置richText.text = "....[url=xxxx]...[/url]....."，赋值的字符串里面有这种url的，会报错误，但是不太好重现。想知道是我们哪个地方没使用正确。下面是报错信息。
NullRefrerenceException:Object refrence not set to an instance of an object FairyGUI.Utils.HtmlLink.SetArea(System.Int 32 startLine, System.Single startCharX, System.Int32 endLine, System.Single endCharX)
FairyGUI.TextField.BuildMesh()
FairyGUI.TextField.Redraw()
FairyGUI.RichTextField.Update()

**Comment by xiaoguzhu** [comment]
只给个结果，无从知道。

**Comment by pl01898759** [comment]
就是没法重现，我也不知道过程是怎样的，请问谷主，能给几个方向吗？会有些什么可能，我好尝试下。多谢
