### ISSUE TITLE
关于富文本那个，发现了点问题

### ISSUE THREAD

**Issue by pl01898759** [fairygui/FairyGUI-unity#116]
RichTextField.cs这个类里面，Dispose()的时候，调用了CleanupObjects，但是没有把textField.htmlElements清空，如果有人在调用了销毁后，还继续对这个文本执行赋值操作（当然这样操作是不允许的，但是代码那么多，有时候有人不小心这么做了不好发现。），那么会在BuildLines里面重新又调用一次CleanupObjects，这个时候就会把同样的htmlObject多次放回池里面。接下来就有可能同一个htmlObject被多个文本同时使用了。就导致一些问题。

public override void Dispose()
{
	if (_disposed)
		return;

	CleanupObjects();
	base.Dispose();
}

internal void CleanupObjects()
{
	List<HtmlElement> elements = textField.htmlElements;
	int count = elements.Count;
	for (int i = 0; i < count; i++)
	{
		HtmlElement element = elements[i];
		if (element.htmlObject != null)
		{
			element.htmlObject.Remove();
			htmlPageContext.FreeObject(element.htmlObject);
		}
	}
}

**Comment by xiaoguzhu** [comment]
Dispose了还能继续操作？如果你是c++，直接给你一个crash。

**Comment by pl01898759** [comment]
> Dispose了还能继续操作？如果你是c++，直接给你一个crash。

我知道是不应该调用，但是dispose掉的文本，赋值是不会报错的。也没有啥反馈，写代码的人有时候，没留意就这样了。如果真给我crash掉了还好说，我还能查到是这个原因。

**Comment by pl01898759** [comment]
而且肯定不是下面这种接着写的。
tf:Dispose()
tf.text = "asd"

我们现在遇到的情况就是一个界面里面有个文本，一个按钮。
按钮点击后，会触发一个回调，然后代码是接着就赋值文本的。
问题就出在这个回调方法会直接把整个界面关闭销毁了。这样就导致了文本也销毁了，然后又赋值。
整个游戏里面这种情况说不准就会发生。
引擎这边应该是可以直接避免这种情况的。
