### ISSUE TITLE
FairyGUI-Editor传出的IPublishData，会因为界面包含普通组出错

### ISSUE THREAD

**Issue by qufangliu** [fairygui/FairyGUI-unity#117]
如果界面中包含了一个普通组，在FairyGUI-Editor插件获取到的IPublishData中，部分UI组件的index会比正确值多1。

**Comment by qufangliu** [comment]
测试后发现，每个普通组，都会导致在Editor显示列表下方的UI组件的Index+1

**Comment by xiaoguzhu** [comment]
哪里的索引？

**Comment by qufangliu** [comment]
IPublishData.outputClass的members列表中，每个元素的index，用于GetChildAt()的参数。
![image](https://user-images.githubusercontent.com/9823449/69853814-c7026600-12c2-11ea-9ab0-9099fba9133b.png)

**Comment by qufangliu** [comment]
虽然这里注释没有写出，这个对象打印出来是有记录index的。希望插件也能使用index，因为通过name获取Child的方法必须去遍历整个children列表，效率相比index会更低。
![image](https://user-images.githubusercontent.com/9823449/69854102-35472880-12c3-11ea-9698-d375eba41f05.png)

**Comment by qufangliu** [comment]
对于我们的需求来说，普通组不需要添加DisplayObject在_children中，也不需要被get到。不知道在什么情况想需要获取普通组。

**Comment by xiaoguzhu** [comment]
不是给的一个数组吗，索引不就是在数组里的顺序？

**Comment by qufangliu** [comment]
索引是在数组里的顺序，但是IPublishData中的索引是错误的，IPublishData受普通组影响，ui组件索引比正确的多了1。
![image](https://user-images.githubusercontent.com/9823449/69858302-afc87600-12cc-11ea-8b70-1fd73fed998a.png)

**Comment by qufangliu** [comment]
C#代码能生成对，也就是说明在生成代码时有对普通组进行过处理的，希望IPublishData是在做过导出处理后再给到插件。

**Comment by xiaoguzhu** [comment]
还是不明白IPublishData哪里给你索引。注释很清楚，就是一个members数组。你要用getchild，那就是数组的索引。
