### ISSUE TITLE
Facing item Renderer problem.

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#12]
Hi!

i m facing problem in making ItemRenderer.
1-created itemrender as usual
2-make a child label.
3-label Width connect with container width.

container height connected with label hight.

(i have simplified this problem here but even applying there steps you will find problem)    

[item Renderer problem + projects](https://we.tl/SYflvAxRLO)

**Comment by fairygui** [comment]
This is a problem. But..are you developing a web program? On mobile platform, the screen size would not change frequently like this case. Let me mark it as a enhancement. Solution for now is to call GList.numItems or GList.RefreshVirtualList on screen size changed.

**Comment by aammfe** [comment]
both , its like a forum.
