### ISSUE TITLE
GLoader.color is not applied to GImage down the hierarchy

### ISSUE THREAD

**Issue by jimon** [fairygui/FairyGUI-unity#123]
I have a component that have a structure like this:
- Group
  - Image1
  - Image2
  - ...

I don't have colors exported as properties and I don't have controllers on them.

Then I load this component via loader and set the color in loader. In FairyGUI Editor this seems to apply color to all images in hierarchy. But in FairyGUI-unity it does not.

Looking in implementation of loader.color setter it seems it expects to have a gear there.

What is expected behavior here? Editor is wrong?

**Comment by xiaoguzhu** [comment]
No, it will not. It only applies to the contained image. The behavior of Editor is wrong and I'll fix that in next version.
