### ISSUE TITLE
MakeFullScreen is not effective

### ISSUE THREAD

**Issue by jimon** [fairygui/FairyGUI-unity#124]
I'm doing my own screen transition setup so I need to manually control which components are present.

In my setup first I do `GRoot.inst.SetContentScaleFactor(300, 500, UIContentScaler.ScreenMatchMode.MatchWidthOrHeight);` to set correct proportions.
Then I load components as `UIPackage.CreateObject("main", "XXX").asCom`.
And then I show/hide screens via `GRoot.inst.AddChild(XXX);`

In additional when screen size changes (and on startup) I call the following method:
```
void UpdateScreenSize()
{
    int scaledWidth = Mathf.CeilToInt(Screen.width / UIContentScaler.scaleFactor);
    int scaledHeight = Mathf.CeilToInt(Screen.height / UIContentScaler.scaleFactor);
    GRoot.inst.SetSize(scaledWidth, scaledHeight);
    GRoot.inst.SetXY(0, 0);
    foreach (var p in _screens)
        p.Value.MakeFullScreen();
}
```

The problem is that GList/ScrollPane inside somehow gets the wrong size (or bounding box?) and my content is only partially shown.

In the following video you can observe the problem, I'm changing size of a child of `GRoot.inst`, then it somehow retriggers something and problem fixes itself. If I change size of `GRoot.inst` then problem doesn't fix itself.

https://drive.google.com/file/d/11m1mPr1SIUUESVnJ74DlCV-tIRIzw_iQ/view?usp=sharing

Is there something I'm missing when I doing manual `AddChild`?

**Comment by jimon** [comment]
Ok managed to hot fix it via triggering resize on all objects:
```
void UpdateScreenSize()
{
    int scaledWidth = Mathf.CeilToInt(Screen.width / UIContentScaler.scaleFactor);
    int scaledHeight = Mathf.CeilToInt(Screen.height / UIContentScaler.scaleFactor);
    GRoot.inst.SetSize(scaledWidth, scaledHeight);
    GRoot.inst.SetXY(0, 0);
    foreach (var p in _screens)
        p.Value.MakeFullScreen();
    _bg.MakeFullScreen();

    Action<GObject> hotFix = null;
    hotFix = obj => {
        obj.SetSize(obj.width - 1, obj.height - 1);
        obj.SetSize(obj.width + 1, obj.height + 1);
        if (obj is GComponent)
            foreach (var child in obj.asCom.GetChildren())
                hotFix(child);
    };
    hotFix(GRoot.inst);
}
```
But that's not great :)

**Comment by xiaoguzhu** [comment]
You should not change the size of Groot. Its always the logical screen size. Read this https://en.fairygui.com/docs/guide/editor/adaptation.html

**Comment by jimon** [comment]
Ok, so I only need to call `MakeFullScreen` on my components and it should be enough? Thanks!

**Comment by jimon** [comment]
Ok this is what I'm doing now:
I've removed `GRoot.inst.SetContentScaleFactor` from my code and updated my screen size handler method as following:
```
    void UpdateScreenSize()
    {
        var size = new Vector2Int(Screen.width, Screen.height);
        //if (_cachedScreenSize != size && _screens != null)
        {
            _cachedScreenSize = size;
            foreach (var p in _screens)
                p.Value.MakeFullScreen();
        }
    }
```
Two problems:
1) If I'm doing check if screen size changed (the `if` in the method), then changing inspector viewport size in Unity doesn't update layout of UI.
2) Starting in 16:9 landscape layout, changing to 16:9 vertical layout and back to 16:9 landscape, it breaks propagation of something on `GList`, here on screenshot you can see the issue as in scene view there are many sprites outlines are visible yet in game view they are not visible:

![image](https://user-images.githubusercontent.com/1333661/77574996-22d8a680-6ed3-11ea-8c8c-d71242e9e819.png)

As I mentioned in first post and in the video, just changing the size of elements slightly makes them appear again. Any tips where should I look to find the problem?
