### ISSUE TITLE
Nested common group gets incorrect layout when placed inside vertical/horizontal layout group

### ISSUE THREAD

**Issue by jimon** [fairygui/FairyGUI-unity#126]
I have a layout where I have a root vertical layout group and nested group which contains a few images

```
- n1 (Vertical layout group, relationship container width->width, height->height)
  |- n2 (Common group)
  |  |- n3 (Image, relationship n2 width->width, height->height)
  |  |- n4 (Image, relationship n2 width->width, height->height)
  |- n5 (Image)
```

What I see in the editor: n3 & n4 are placed together and n5 below them
What I see in Unity: n3, n4, n5 are placed below each other, it seems like unity runtime ignores n2

If I change n2 to be advanced group with no layout, problem fixes itself.

**Comment by xiaoguzhu** [comment]
common group is removed on publish. It's for editor but not runtime.
