### ISSUE TITLE
有计划支持Addressables加载嘛？

### ISSUE THREAD

**Issue by frank28** [fairygui/FairyGUI-unity#128]
Addressables是unity新的资源加载方式，基于AssetBundle
https://docs.unity3d.com/Manual/com.unity.addressables.html

FairyGUI目前支持的方式是AB或者Resources.Load，与Addressables不兼容的点在于只支持阻塞同步加载的模式，而Addressables只支持异步加载模式。

有加入支持Addressables加载方式的计划吗？或者是将加载方式全面改为支持异步？

**Comment by xiaoguzhu** [comment]
自己改UIPackage就行了

**Comment by frank28** [comment]
不是很明白，具体是改哪一部分？我看到的主要问题是AddPackage中调用自定义loadFunc，都是假定loadFunc是同步返回的
` TextAsset asset = (TextAsset)loadFunc(assetPath + "_fui", ".bytes", typeof(TextAsset), out dm);`
这里和Addressables要求的异步似乎不兼容？

**Comment by xiaoguzhu** [comment]
你需要在UIPackage载入时就把资源全部通过异步的方式载入好。然后这里的方法只是从缓存里拿出来。

**Comment by HiKit** [comment]
这里有个问题，如果一个package有多个atlas，我无法根据fui.bytes去推算出需要加载哪些atlas，这样就需要我自己在打包时去维护这个关系
