### ISSUE TITLE
Better Approach to make Emoji Like Chat UI

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#13]
Hi!
i was wondering why you are using poll and adding child directly..?
instead of increasing list.numItems ..?
"i have not seen any example of using list.data"

list is also not set to virtualized , instead you are explicitly checking its childCount and adding them in pool.
yes there are two item renderers , therefore you are using this thing. 

but is there any better way we can adopt while using more then one itemRenderers , with virtualization as and not adding child directly to list..?

**Comment by fairygui** [comment]
Look at Example 26 - EmojiPro

**Comment by aammfe** [comment]
:) thanx you r brilliant man ..

**Comment by aammfe** [comment]
Every thing we are doing is in Same Class.

A possible Solution for Separating ItemRenderer Login , form Main Class.   

means there would be other class named "MessageItemRenderer" implementing an interface "IItemRenderer" , IItemRenderer has functions like

CommitData(int index, GObject obj    , Data object) ,
ItemProvider(Data object) ,

it could also have a function "LayoutContent"  so we can layout its children according to data after invalidation.

 listView.ItemRendererClass = MessageItemRenderer;

now both are separated...

**Comment by fairygui** [comment]
Just call RefreshVirtualList or set numItems again.

**Comment by aammfe** [comment]
i think i could not make last post clear ,

let me explain it again.

right now we have to place itemRenderer code and list code in one class.

but thing i m trying to say is to separate these two... list code , and itemRenderer code .
just like feathers?

**Comment by fairygui** [comment]
class a
{
   var list;
   void a(list) { this.list = list; list.itemRenderer = itemRender; list.itemProvider = itemProvider;}
   void itemRenderer() {}
  void  itemProvider() {}
}

**Comment by aammfe** [comment]
yep here we have to pass listData as well to constructor..

but in feathers approach things are quite clean...
