### ISSUE TITLE
能不能提供一个只有纯净SDK的工程或者UnityPackage？

### ISSUE THREAD

**Issue by Miucann** [fairygui/FairyGUI-unity#131]
目前在GitHub上貌似只能下载带案例的工程，没有纯净的只含有sdk的工程。自己去删案例什么的，比较麻烦，而且还不知道会不会错删，漏删等等

**Comment by xiaoguzhu** [comment]
不会错删，也不会漏删，把Examples目录整个删掉就可以了。

**Comment by wkStark** [comment]
> 不会错删，也不会漏删，把Examples目录整个删掉就可以了。

ok，谢谢

**Comment by Miucann** [comment]
> 不会错删，也不会漏删，把Examples目录整个删掉就可以了。

我看除了Examples文件夹外，还有其他的诸如Resource文件夹下也有东西，StreamingAssets下还有AB包，还有_TerrainAutoUpgrade文件夹等等，这些都是FGUI的必须需要的，还是？

**Comment by xiaoguzhu** [comment]
其他都是要的。StreamingAssets是动态打包的东西，肯定是不需要的。再打包就没有了。

**Comment by Miucann** [comment]
> 其他都是要的。StreamingAssets是动态打包的东西，肯定是不需要的。再打包就没有了。

感谢回复，再请问一下，文件的目录结构可以调整吗？比如Script下的文件，把他们移到一个文件夹下，或者重命名Script文件夹等，是否可以这样操作？

**Comment by xiaoguzhu** [comment]
这些是unity的知识啊。。和UI无关。

**Comment by Miucann** [comment]
> 这些是unity的知识啊。。和UI无关。

额，我知道，我是怕你们源码中会不会写了一些固定加载路径之类的，怕改了名字，移动了位置导致出问题。谢谢

**Comment by rocwood** [comment]
> > 这些是unity的知识啊。。和UI无关。
> 额，我知道，我是怕你们源码中会不会写了一些固定加载路径之类的，怕改了名字，移动了位置导致出问题。谢谢

大部分时候自己试一试就好了，也就是删掉Examples和StreamingAssets。
至于这么成熟的库有没有硬编码路径的低级问题，大家都应该要有自己的判断。

**Comment by hqpko** [comment]
Unity’s Package Manager?
