### ISSUE TITLE
input Text设置了最大长度，输入超过最大长度会报错

### ISSUE THREAD

**Issue by willy8811** [fairygui/FairyGUI-unity#136]
![QQ图片20200525104351](https://user-images.githubusercontent.com/49179493/82773486-c19e6680-9e74-11ea-9195-cae57d7504c4.png)
![QQ图片20200525104358](https://user-images.githubusercontent.com/49179493/82773505-c95e0b00-9e74-11ea-8065-322661ce605c.png)

**Comment by willy8811** [comment]
用的是2020.1.0p9版本的编辑器，SDK代码已更到最新

**Comment by xiaoguzhu** [comment]
https://github.com/fairygui/FairyGUI-unity/commit/381f35755b325b092310c96160dc85ba76ca9449
