### ISSUE TITLE
使用URP 并打开SRP Batcher 会导致部分UI渲染错误

### ISSUE THREAD

**Issue by Difficulty-in-naming** [fairygui/FairyGUI-unity#139]
![image](https://user-images.githubusercontent.com/8246779/88996013-b6f1c900-d31e-11ea-946e-060c1ab60b6b.png)
按钮文本丢失

![image](https://user-images.githubusercontent.com/8246779/88995953-8873ee00-d31e-11ea-97a6-2d11592429ad.png)
裁剪失效

![image](https://user-images.githubusercontent.com/8246779/88996067-d557c480-d31e-11ea-9fda-c0b365fd2b6d.png)
进度条不渲染

**Comment by GaLeGayGay** [comment]
在使用URP的情况下关闭SRP Batcher 也会导致部分UI渲染错误.但错误的范围要小的多.我可以把工程发到你的邮箱里面.

**Comment by xiaoguzhu** [comment]
需要对着色器FairyGUI-Text和FairyGUI-Image做如下修改：

![QQ20200724-120929](https://user-images.githubusercontent.com/38777031/89030788-c7786280-d363-11ea-9e36-bb7b88626a3b.png)

**Comment by SunHowe** [comment]
UnityPerMaterial CBuffer包含的属性部分似乎不能有宏定义 否则属性布局变动会导致SRPBatcher不生效。shader面板上会有相关报错信息:
![2bd45f90c8d3e3f20f7d0ce42f71c28a](https://github.com/fairygui/FairyGUI-unity/assets/12583154/bd487ee5-cd70-4505-99d7-c6542cc851d4)

以及_ClipBox和_ClipSoftness需要标注在属性上
![f3a2ab9f49cf3a0b9bfdca0159946947](https://github.com/fairygui/FairyGUI-unity/assets/12583154/3b596a87-3b99-4e6e-8c5d-b4d4dadeea7e)
