### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#14]
Kindly Can you Define your Road Map ..?
what are your future planes for this , what things you are going to introduce in next versions.
just roughly , to get idea ..

**Comment by fairygui** [comment]
1.7.x is a mile stone version, I am now focusing in bug fixes and small enhancements.
Feathers now we have covered nearly all needs for creating a game.
And I need to spend time to write more articles about them.

**Comment by aammfe** [comment]
Great , can i expect screen , Screen navigation , drawers,
this like this builtin in editor?

**Comment by fairygui** [comment]
No screen principles in editor, they can be implemented by code. You can port starling code.
I have answer for how to create drawers in another issue.
