### ISSUE TITLE
fairy gui的一些问题

### ISSUE THREAD

**Issue by ffbh123456** [fairygui/FairyGUI-unity#141]
1.导入fairy-gui后unity 2019.4 LTS 报错
<img width="575" alt="截屏2020-08-27 下午9 39 08" src="https://user-images.githubusercontent.com/20750357/91449472-be6ca980-e8ad-11ea-92bc-1c8cff533cb5.png">
<img width="806" alt="截屏2020-08-27 下午9 39 28" src="https://user-images.githubusercontent.com/20750357/91449504-ca586b80-e8ad-11ea-8bef-66b6285c402c.png">
2.asset放置在streamingassets目录下面不太好，建议统一放置在FairyGUI目录，这样更方便管理
<img width="625" alt="截屏2020-08-27 下午9 39 43" src="https://user-images.githubusercontent.com/20750357/91449550-d3493d00-e8ad-11ea-8364-8591c0d39698.png">

**Comment by xiaoguzhu** [comment]
问题1 meta文件报错，在最后一个commit已经解决过了，其实就是把meta文件都删掉就行了。那个缺少UnityEditor的提示，我测试没发现，文件里也的确有using UnityEditor。
问题2 那些都是Examples里生成的内容，直接删掉就行了。

**Comment by ffbh123456** [comment]
@xiaoguzhu 
关于using UnityEditor这个问题：你使用的是unity 2019 LTS吗，我这边需要在代码里显示的继承UnityEditor.Editor才能编译通过

**Comment by xiaoguzhu** [comment]
我用2019.3.0，应该没有什么区别

**Comment by ffbh123456** [comment]
@xiaoguzhu 
你可以试着升级到LTS，我感觉是unity版本的问题

**Comment by xiaoguzhu** [comment]
也测试过

**Comment by ffbh123456** [comment]
可能我和你的project setting不一样，你用的api level是？

**Comment by xiaoguzhu** [comment]
.net standard2.0 和 .next 4.x 都切换过了。没问题。
