### ISSUE TITLE
边缘带透明的图片，拖入组件中，如果进行过翻转，编辑器跟Unity中的表现不一致

### ISSUE THREAD

**Issue by xihuananjingdelzc** [fairygui/FairyGUI-unity#148]
1. 图片的右侧以及底部存在透明边缘
2. 锚点设置为右上（同时拖入的图片放于右上角）
3. 图片没有设置禁止裁剪边缘空白
4. 拖入组件的图片设置为左右翻转
5. 该组件设置为全屏

在编辑器下表现正常，unity中因为mesh生成的实际小一点，然后进行ui的翻转会导致最右侧存在透明边缘那么大的空隙

**Comment by xiaoguzhu** [comment]
我找个时间测试一下
