### ISSUE TITLE
list Inertia get Disabled 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#15]
[problem](https://we.tl/XlPc45Rx1p)

after this layout code , during Scrolling list inertia some time get disabled 

` private void RenderListItem(int index, GObject item)
    {

        var button = item.asButton;

        var icon = button.GetChild("icon");
        var backGround = button.GetChild("backGround");
        var label = button.GetChild("text");

        var randomNo = UnityEngine.Random.Range(2, 10);

        var str = Path.GetRandomFileName();

        for (int i = 0; i < randomNo; i++)
        {
            str += Path.GetRandomFileName();
        }

        label.text = str;

        
        //        layout

        
        var margin = 10;
        icon.xy = new Vector2(margin, margin);

        label.width = button.width - 40 - icon.x - icon.width;

        backGround.height = label.height + margin;
        backGround.width = label.width + margin;

        backGround.x = icon.x + icon.width + margin * 2;
        backGround.y = 5;

        label.x = backGround.x + 5;
        label.y = backGround.y + 5;

        button.height = backGround.y + backGround.height + 5;
        
    }`

**Comment by fairygui** [comment]
Fixed in 1.7.3. Please check.
