### ISSUE TITLE
question about StageEngine  OnGUI method？

### ISSUE THREAD

**Issue by justinlm** [fairygui/FairyGUI-unity#151]
If my game does not use any of the unity  IMGUI things，can I comment the OnGUI method？

**Comment by xiaoguzhu** [comment]
useGUILayout = false is set in StageEngine.Start, so OnGUI is GC friendly. OnGUI handles some logic about keyboard and mousewheel, I suggested you should keep it.

**Comment by justinlm** [comment]
OK, I see. Thank you very much for your answer.
