### ISSUE TITLE
Label Width problem

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#16]
i want chat like this list items but

label configuration 1 [this](http://prntscr.com/d5shel)

layout code 

` var margin = 10;

        icon.xy = new Vector2(margin, 5);
        var iconAsociatedHeight = icon.y + icon.height + margin;

        label.x = icon.x + icon.width + margin * 2;
        label.y = icon.y;

        var labelWidth = button.width - label.x - 10;

        if (label.width > labelWidth)
        {
            label.width = labelWidth;
        }

        backGround.x = label.x - 5;
        backGround.y = label.y - 5;

        backGround.height = label.height + 10;
        backGround.width = label.width + 10;

        var textAssoicatedHeight = backGround.y + backGround.height + 5;

        button.height =  Math.Max(textAssoicatedHeight, iconAsociatedHeight);`

[result](http://prntscr.com/d5si1r)

lable configuration 2 [this](http://prntscr.com/d5si6e)
code Same

[result](http://prntscr.com/d5sigl)

**Comment by aammfe** [comment]
possible solution any tip..?
 label.autoSize = AutoSizeType.Both;


        var labelWidth = button.width - label.x - margin *3;
        if (label.width > labelWidth)
        {
            label.autoSize = AutoSizeType.Height;
            label.width = labelWidth;
        }
        ``

**Comment by aammfe** [comment]
possible solution but is there any other way ..?

`

label.autoSize = AutoSizeType.Both;
      var labelWidth = button.width - label.x - margin *3;
       if (label.width > labelWidth)
        {
            label.autoSize = AutoSizeType.Height;
            label.width = labelWidth;
        }

```
    `
```

**Comment by fairygui** [comment]
Would you have a try with the latest code?
