### ISSUE TITLE
当在 GList 回弹时，连续点击其他未选中的 Cell 区域，回弹无法结束

### ISSUE THREAD

**Issue by UltraREX** [fairygui/FairyGUI-unity#164]
GList 开启回弹效果后（以竖排竖向滚动为例），在回弹过程中，用鼠标连续点击列表内其他未选中的 Cell，回弹相关值逐渐减小为： _tweenStart 为 (0.0, -1.0) _tweenChange 为 (0.0,1.0)，endPos 为 (0.0, 0.0) ，导致回弹一直不结束，从而期望选中的 Cell 也一直无法被选中。

**Comment by xiaoguzhu** [comment]
这种情况，是不是再点一下就恢复正常，如果是，我觉得不用处理。

**Comment by UltraREX** [comment]
> 这种情况，是不是再点一下就恢复正常，如果是，我觉得不用处理。

如果是一直连续点击不会，如果是等回弹时间结束再点击，恢复正常。
