### ISSUE TITLE
目前动效想要调整位置的时候会和适配出现冲突

### ISSUE THREAD

**Issue by haomingge** [fairygui/FairyGUI-unity#167]
比如想要让一个group在屏幕中心移动，如果仅仅靠记录百分比依旧会造成位置不准确的问题
或者想要让一个右对右的原件，做一些位移动效，也是没法实现的，
如果可以支持一个相对当前位置的位移配置或许能解决这些问题

**Comment by xiaoguzhu** [comment]
是的,可能要添加新的机制去实现,等以后改进
