### ISSUE TITLE
Question about TextMeshPro support (crisp text?)

### ISSUE THREAD

**Issue by PascalSoftwares** [fairygui/FairyGUI-unity#169]
I saw TextMeshPro related codes in project (saying took code from TMP, supporting features etc), and issues talking about 'crisp option' But not sure what exactly it is.
Can you explain what's the feature (on/off option in editor | property in fairygui object | setting unity component like shader replacement...) and how to use it?

**Comment by xiaoguzhu** [comment]
1.Import a ttf font into editor
2. double click the font in library panel
3. switch render mode  to sdfaa.
4. drag the font to the font input filed.
