### ISSUE TITLE
'Generate Mip Maps=unchecked' suggestion alert message

### ISSUE THREAD

**Issue by PascalSoftwares** [fairygui/FairyGUI-unity#172]
FairyGUI shows warning message of

FairyGUI: settings for 'Assets/Resources/FGUIEditor/Basic_atlas0.png' is wrong! Correct values are: (Generate Mip Maps=unchecked)

when loading atlas.
I couldn't find Mipmap option in Publish Settings or Editor Preference. where can I find it?

**Comment by xiaoguzhu** [comment]
Find it in Unity. Select Basic_atlas0.png and see inspector.
