### ISSUE TITLE
编辑器导出锚点问题

### ISSUE THREAD

**Issue by leelnfei** [fairygui/FairyGUI-unity#173]
轴心保持左上，勾选同时作为锚点，导出的包没有生效，读取一致是false
if (buffer.ReadBool())
 {
                f1 = buffer.ReadFloat();
                f2 = buffer.ReadFloat();
                SetPivot(f1, f2, buffer.ReadBool());
}

**Comment by xiaoguzhu** [comment]
你可能是在组件的模板里设置了这个，又在组件的实例里设置了这个，那就要注意了。

**Comment by leelnfei** [comment]
![(6E4UYEFJ1K~4RU${2SRW_T](https://user-images.githubusercontent.com/6847830/142619229-4d2ad556-f13b-4593-b04e-b44540afac37.png)
![{APS$L0Q{T$2}(K5G5 81YC](https://user-images.githubusercontent.com/6847830/142619238-52897cc1-8efb-41c2-82d5-31386968b563.png)

这个是都勾选了同时作为锚点导出的xml文件，一个上面的选择轴心是中心，下面轴心是左上角

**Comment by leelnfei** [comment]
这个是都勾选了同时作为锚点导出的xml文件

**Comment by xiaoguzhu** [comment]
左上角就代表使用模板设置，不会覆盖。
