### ISSUE TITLE
UIPackage.AddPackage 里 desc.Unload(true); 时没有判断unloadBundleByFGUI

### ISSUE THREAD

**Issue by IcePower** [fairygui/FairyGUI-unity#181]
这个重载里：
public static UIPackage AddPackage(AssetBundle desc, AssetBundle res, string mainAssetName)
...

if (desc != res)                //  这里应该为 if (unloadBundleByFGUI && desc != res) 吧？
     desc.Unload(true);

**Comment by xiaoguzhu** [comment]
改了
