### ISSUE TITLE
GList 嵌套 GList 的时候，嵌套的GList数据源不大好获取

### ISSUE THREAD

**Issue by zxl8795757** [fairygui/FairyGUI-unity#192]
因为GList只负责刷新对象，不负责保存数据导致的这个问题产生，Laya的List就是直接把数据源传到List内部，然后绑定在渲染的每个对象上，到时候直接在 itemRenderer 里面直接获取即可。
感觉GList也可以参考使用，用起来比较方便。我有尝试改了源码，但是好像push不上去。或者有没有其他办法可以获取？

**Comment by xiaoguzhu** [comment]
目前GList是没有数据绑定功能的。只是提供了 render回调这样一个传递的功能，所以还是要自己实现
