### ISSUE TITLE
UPM结构支持

### ISSUE THREAD

**Issue by DonnYep** [fairygui/FairyGUI-unity#194]
官方是否考虑支持UPM文件结构？

**Comment by qipa** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在忙碌中，无法亲自回复您的邮件，之后将尽快给您回复。

**Comment by chiuan** [comment]
可以直接用我的库的版本，再upm窗口添加git url
`
https://github.com/chiuan/FairyGUI-unity.git?path=Assets/Plugins/FairyGUI
`
