### ISSUE TITLE
Button hover sound effect?

### ISSUE THREAD

**Issue by PascalSoftwares** [fairygui/FairyGUI-unity#195]
There is a 'Sound' property in FGUI editor's Button inspector which is played when clicked, but how I can assign a sound for 'starting mouse hover'? 'Etc-Enter Sound' property is played when button is displayed, and button controller does not have sound effect action.

**Comment by xiaoguzhu** [comment]
you may play a transition on hover page

**Comment by PascalSoftwares** [comment]
Thank you. writing step by step configuration I found.

<Editor>
1. Left panel - Transitions - Add new
2. Double click to enter transition editor
3. Right click center panel - component background to add new timeline item for transition 
4. Choose Play sound
5. Select sound container from bottom panel - timeline editor
6. Drag sound resource to right panel - Frame Value - Sound
7. Click center panel - right top Quit to exit transition editor
8. Click center panel - left top botton controller
9. Add (+) Action, from normal state (0) to hover state (2)
10. Select created transition from combo box
