### ISSUE TITLE
Duplicated font Render Mode - SDFAA

### ISSUE THREAD

**Issue by PascalSoftwares** [fairygui/FairyGUI-unity#196]
In Fairygui editor's font property, there is 2 duplicated SDFAA option for Render Mode ::

Smooth / SDFAA / Hinted Raster / SDFAA .

Is there any difference between second one and fourth one?

**Comment by xiaoguzhu** [comment]
https://docs.unity3d.com/2019.1/Documentation/ScriptReference/TextCore.LowLevel.GlyphRenderMode.html

**Comment by PascalSoftwares** [comment]
> https://docs.unity3d.com/2019.1/Documentation/ScriptReference/TextCore.LowLevel.GlyphRenderMode.html

There is 'SDFAA HINTED' and 'SDFAA' in list of 10 options. Do you mean that those two? If so, which 'SDFAA' in fairygui editor means 'hinted' one?

**Comment by xiaoguzhu** [comment]
SDFAA in editor only means to use TMP to render text. The specific mode needs to be set in the font resources of Unity.

**Comment by PascalSoftwares** [comment]
> SDFAA in editor only means to use TMP to render text. The specific mode needs to be set in the font resources of Unity.

You mean that both selection items works exactly same, setting renderer to TMP?
