### ISSUE TITLE
Some Queries

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#2]
Thanx For This Great Asset 👍 
There is no other UI asset  on assetStore even closer to it. 

i just started learning it.
i have some queries.

1- Constant Physical size is same on mobile , these are my  [settings](http://prntscr.com/czlh7i)

2- Image height and width both are associated with Controller height and Width , image resize well in fairy Editor [Iphone 5](http://prntscr.com/czlig3)          [Ipad](http://prntscr.com/czljww) but in unity editor, it remains designer [size](http://prntscr.com/czllwo) and  do not resize to game view ,it should fill game view. if i m doing wrong plz correct me..

3- i have tried to increase scrolling speed by "_list.scrollPane.scrollSpeed = 300" but no effect.

4-i could not understand majority of tutorials because all are in chines expect "FairyGUI Tutorials 1"

**Comment by fairygui** [comment]
1 - I have made a fix for this bug just now.
2 - You must set the size yourself in Game. GRoot.inst.width/height is the logic screen size. e.g. yourComponent.size = GRoot.size. Or if you use UIPanel, just set FitScreen to 'Fit Size'.
3 - 'scrollSpeed' currently only effected on PC. I'll improve it later.
4 - Need some time to add more English tutorials.

**Comment by aammfe** [comment]
and other potential bug ,
1- Make a list.
2- Layout Flow Horizontal
3- List height and width associated controllers height and width , FitSceen ='fit Size'
4- item size is 150 , 35
5- list.numItems = 1000;

now you will see tile view , and by decreasing width of game view also decrease tile columns.
after column Count =  1 , , if you will decrease More you will find Error 

"DivideByZeroException: Division by zero
FairyGUI.GList.HandleScroll1 (Boolean forceUpdate) (at d:/FairyGUI-unity/Scripts/UI/GList.cs:1511)
FairyGUI.GList.HandleScroll (Boolean forceUpdate) (at d:/FairyGUI-unity/Scripts/UI/GList.cs:1379)
FairyGUI.GList.RefreshVirtualList (System.Object param) (at d:/FairyGUI-unity/Scripts/UI/GList.cs:1246)
FairyGUI.Timers.Update () (at d:/FairyGUI-unity/Scripts/Utils/Timers.cs:210)
UnityEngine.Debug:LogException(Exception)
FairyGUI.Timers:Update() (at d:/FairyGUI-unity/Scripts/Utils/Timers.cs:216)
FairyGUI.TimersEngine:Update() (at d:/FairyGUI-unity/Scripts/Utils/Timers.cs:272)
"

**Comment by aammfe** [comment]
how to set list view children to horizontallyAlign = "Middle"  ..? [image](http://prntscr.com/czxsyq)

**Comment by fairygui** [comment]
That's a bug, I made a fix.

You can use margins to align the items.

**Comment by MrKylinGithub** [comment]
mark...

**Comment by aammfe** [comment]
plz check there, [gif1](https://we.tl/sHaSPTCEzY) [gif2](https://we.tl/SHUb6bLHOs)

**Comment by aammfe** [comment]
means we have to manually set margin  ..? and List.pivotx does not effect on items?
[list](http://prnt.sc/czybyv)

**Comment by aammfe** [comment]
using Fairy GUI how i can Achieve this ? 
[pagination horizontal List ](http://techpearls.com/ilih/)

**Comment by fairygui** [comment]
Yes, you need to set margin manually.
The bug shown in gif I have marked it down and fix it later.
An option named 'Page Mode' is provided. See below:
![image](https://cloud.githubusercontent.com/assets/9907813/19800812/12711ba2-9d2f-11e6-89c3-6b81afbcd618.png)

**Comment by aammfe** [comment]
so what  will be effect of pivot ..?
kindly introduce horizontally align in Component , so we dont have to do it manually.

Thanx :)

**Comment by fairygui** [comment]
pivot is used for rotation, scale, etc.
Or you can align the whole list.

**Comment by aammfe** [comment]
thanx :)

**Comment by aammfe** [comment]
[Horizontal Pagination List](http://techpearls.com/ilih/) in this example
When width change it draw only items which can fit in , means no extra cutting item , but here things are not as same , [Fairy ui](https://we.tl/vBI2KrvL6n)

Feathers UI uses concept of pages so when you say 10 items in a page then UI always show 10 items even if UI is able to show 20, so if you can implement something like that in future (After fixing all current list related issues) that’d be great  [feathers Example](https://feathersui.com/examples/tile-list/)

**Comment by fairygui** [comment]
Get what you want. Suggest to create a standalone issue for this feature. I'll consider of it later.

**Comment by aammfe** [comment]
Thanx

**Comment by fairygui** [comment]
The bug mention here [https://we.tl/sHaSPTCEzY](url) I have fixed. Please check.
This issue is closed. Welcome for any queries or advices in new thread. Suggest that bug report or feather request should be in single thread.
