### ISSUE TITLE
bug:当将项目设置为播放时不重新载入程序集时，反复播放会出现NullRef异常(Stage下的cacheTransform)

### ISSUE THREAD

**Issue by NicoIer** [fairygui/FairyGUI-unity#202]
![image](https://github.com/fairygui/FairyGUI-unity/assets/91652330/ac2229ea-84fd-4a46-af39-f323217324db)
![image](https://github.com/fairygui/FairyGUI-unity/assets/91652330/7a8204bc-7ae0-4f2d-9d24-74db40093f94)

**Comment by NicoIer** [comment]
![image](https://github.com/fairygui/FairyGUI-unity/assets/91652330/a22fae4c-b49d-4843-8f89-fbeb7ee31ab9)

**Comment by NicoIer** [comment]
![image](https://github.com/fairygui/FairyGUI-unity/assets/91652330/3a32e8d3-ae4a-4594-91bf-25c04793d5b7)

**Comment by NicoIer** [comment]
@libla @yhchen @radarhere @autukill

**Comment by xiaoguzhu** [comment]
fix https://github.com/fairygui/FairyGUI-unity/commit/6f34521fc84e08772e479d3e82e863c447cffab2
