### ISSUE TITLE
TextMeshPro 在 Webgl 平台显示不正确

### ISSUE THREAD

**Issue by zerohualin** [fairygui/FairyGUI-unity#204]
在 Unity Editor 中显示正常 
![企业微信截图_16853548099959](https://github.com/fairygui/FairyGUI-unity/assets/11487350/1c04ece7-6bee-4094-a650-11ba3e4c488e)
在 WEBGL 上显示错误 
![)}HI$A H0SKFFSF7$2~S8GR](https://github.com/fairygui/FairyGUI-unity/assets/11487350/15c25a07-98b0-4ee0-987e-280e3e2d7c47)
TextMeshPro版本 3.0.6

**Comment by xiaoguzhu** [comment]
看看是不是没打包着色器

**Comment by ehyea** [comment]
请问你后面解决了吗？

**Comment by zerohualin** [comment]
> 请问你后面解决了吗？

嗯 我的解决了。问题是这样的：Fairygui 的 TextMeshPro shader 是专门修改过的，但是我项目之前引入过同名的原生shader，导致打包后实际中用了原生的shader。我把原生的shader删掉就好了。
