### ISSUE TITLE
float type 'LineSize' support in Graph component?

### ISSUE THREAD

**Issue by PascalSoftwares** [fairygui/FairyGUI-unity#205]
'Graph' component of ui has property 'LineSize' type of **_int_**, which works as borderline thickness.
But digging in source code, Shape class ( _shape property in GGraph class which get LineSize parameter to draw) actually uses **_float_** LineSize for drawing Rect, Ellipse, Polygon etc.

Is there any possibility to support float-sized LineSize in Graph component?

**Comment by xiaoguzhu** [comment]
This may be a previous mistake, but now it's difficult to change this thing.
