### ISSUE TITLE
Drawers

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#22]
Can you please make SlideBlock as Proper Side Menu with atleast following features
- Push
- Scale Down

If possible also add
- Uncover
- Slide Along
- Slide Out

Here are working examples of [Side Menus](http://semantic-ui.com/modules/sidebar.html#/examples)

**Comment by fairygui** [comment]
It is easy to create these effects by using position control and size control in editor. Please have a try.
