### ISSUE TITLE
Avoid hitting test on invalid positions

### ISSUE THREAD

**Issue by davyzhang** [fairygui/FairyGUI-unity#227]
Screen position out of view frustum (screen pos -nan(ind), -nan(ind), 0.000000) (Camera rect 0 0 1536 2048)

PR:
https://github.com/fairygui/FairyGUI-unity/pull/226

**Comment by xiaoguzhu** [comment]
the pos comes from Input.mousePosition or Mouse.current.position.ReadValue(), I've never come across a situation where they weren't numbers or were infinite, can you explain?

**Comment by davyzhang** [comment]
unity 版本
2022.3.30f1.git.7361922
Revision: 2022.3/staging 70558241b701
Built: Tue, 14 May 2024 21:12:45 GMT

其实就是样例场景, 我把我加的那几行注释掉了就会不停的报错
Example 01 / Example 03 都可以重现

![image](https://github.com/fairygui/FairyGUI-unity/assets/576863/02ddf5ab-4ec4-4a8d-aad9-d446e3c01fae)
![image](https://github.com/fairygui/FairyGUI-unity/assets/576863/c73800a0-dc9d-468f-8b27-5ab904e599f2)


问题可能出在这一行

![image](https://github.com/fairygui/FairyGUI-unity/assets/576863/b99fce29-6daa-4588-bbc5-b03625e209e2)

没有用新的inputSystem 这里拿到的确实是nan

**Comment by davyzhang** [comment]
如果我用了新的input system, 按钮点击又会全部失效, 所有按钮都不能点击了

![image](https://github.com/fairygui/FairyGUI-unity/assets/576863/a45bea1c-d0e7-41dd-b069-1cad0a4d4233)

这个地方在new input system下面一直都是0
![image](https://github.com/fairygui/FairyGUI-unity/assets/576863/a3f848df-ad36-4890-b36e-39f7bfee193d)

**Comment by xiaoguzhu** [comment]
在网上没有找到资料说明在什么情况下Input.mousePosition出现infinite的值，我自己也没能重现，也没见其他人反馈过。你试试换个unity版本，看看是不是特定Unity版本的bug。

**Comment by davyzhang** [comment]
那我先close把, 你后面再观察一下
