### ISSUE TITLE
Scrolling Speed

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#23]
Is there any way to increase List Scrolling Speed ..?

_list.scrollPane.scrollSpeed = 1000;

but it dones not have effect ..

**Comment by aammfe** [comment]
rate of decreasing scrolling--> deceleration rate..([check unity Rec](https://docs.unity3d.com/Manual/script-ScrollRect.html))
there is no way to change this deceleration rate , so list appear to be slow.. plz provide a way to alter it.

**Comment by fairygui** [comment]
Touch scroll speed is increased in 1.7.3, please check.
And added UIConfig.defaultTouchScrollSpeedRatio.

**Comment by aammfe** [comment]
it is working but scrolling is stopping suddenly.....

**Comment by fairygui** [comment]
Suddenly?

**Comment by aammfe** [comment]
Yep , if i increase "UIConfig.defaultTouchScrollSpeedRatio"  list work as assumed but stops suddenly , it does not seems like inertial drag stop. . i should stops lowly.. like mobile lists do

**Comment by fairygui** [comment]
Please try 1.8.0.

**Comment by aammfe** [comment]
i have tested it both desktop ,and mobile , 
on desktop , no one can beat it , but on mobile it is far from production.

on desktop Scroll Sensitivity  is good , but on mobile it is completely opposite.
an other thing constant physical Size is not same on Editor and mobile.

tested example 27.
some changings
1-scale mode -> constant Physical 
2-fit Screen -> non

**Comment by fairygui** [comment]
Thanks for your testing.
can you detail "on mobile it is completely opposite."? Is it slow or fast, or even not responsive?
And is it better if not changing scale mode.

**Comment by aammfe** [comment]
i m last comment i have told you problem about Constant physical size, content scaled up on mobile.
if it is constant physical size it should have same size on every device regardless dpi.

last time i tested on [Samsung S3](http://www.gsmarena.com/samsung_i9300_galaxy_s_iii-4238.php) where content is scaled in this manner when scroll it does not looks good. u have to drag pretty hard to Scroll it. as there is less area to drag.

but now i have recheck on  [huawei p7](http://www.gsmarena.com/huawei_ascend_p7-6124.php)
it has also scaling issue , but list is better here..


as i told you before i have tested your example scene "example 27"
for quick test i change "fit Screen" to "non"
i m [Attaching](https://we.tl/MjdJH4Xr1U) screen shorts of both Phones.

> all above mentioned things are tested on constant Physical Size.

on Consent pixel size it works great on both Phones , as content scale down , and there is more area for dragging.

**Comment by fairygui** [comment]
Got it. I'm check problems for constant physical size.

**Comment by aammfe** [comment]
Hello!!
Is there any update on CONSTANT PHYSICAL SIZE ? I have tested it still  has same issue.

**Comment by fairygui** [comment]
I still don't know about how constant physical size should be. Can you provide me a example?

**Comment by aammfe** [comment]
Constant size like if a button is 1 inch on low DPI phone but it will also 1 inch on retina display.

while using constant physical size when I change default dpi from UI Content Scaler it changes UI size, while unity  UI don't do like this.

While Using unity editor when I select  constant physical size and build on phone UI size is different then unity editor.

and other thing. 

in fairy Editor I m just seeing these two options.

![image](https://user-images.githubusercontent.com/11896817/38008324-76d8d34a-3267-11e8-9dd5-82adaca9856f.png)

it would be great to have constant physical size here too so we can check while editing.

**Comment by fairygui** [comment]
In case the scale mode is constant physical size, and running on PC, how can I determine the content scale factor?

**Comment by aammfe** [comment]
[https://searchcode.com/file/92015486/UnityEngine.UI/UI/Core/Layout/CanvasScaler.cs](/CanvasScaler.cs)

this is how unity UI is working 
from line number 171 HandleConstantPhysicalSize

**Comment by fairygui** [comment]
I have wrote the same code in FairyGUI.UIContentScaler。However, it seems not working right according to your feed back in 19 Feb 2017 in this post,

**Comment by aammfe** [comment]
0k , let me test again.
but I will be able to test it correct if constant physical size is implemented in Fairy GUI editor first so I could compare.

it would be great if you provide these scaling options in fairy gui Editor edit mode , so we know what we are doing.

**Comment by fairygui** [comment]
Content scale policy is not related to 'Scrolling Speed' issue, let's discuss it in issue #62 .
