### ISSUE TITLE
Text Issue

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#24]
Facing About Same Issues in with [Text](https://we.tl/3eAYs7QtpC)

**Comment by fairygui** [comment]
Let me give you an example.

[Forum.zip](https://we.tl/755KKulPMA)

**Comment by aammfe** [comment]
i have simply downloaded your project and open it in unity and facing [this](https://we.tl/ALaN8CEsdx)

**Comment by fairygui** [comment]
Works fine for me. Just check UIContentScaler if its settings is right.
