### ISSUE TITLE
Page indicator

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#25]
Kindly provide [page indicator](https://feathersui.com/help/page-indicator.html) after solving other things.

**Comment by fairygui** [comment]
See Example02-Bag

**Comment by aammfe** [comment]
i have seen it but it is not intractable. 
When clicked , it does not go on its page..

**Comment by aammfe** [comment]
but these are not intractable,
if i click on them , they dont scroll to their page..
