### ISSUE TITLE
Remote Images

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#27]
after seeing IconManager.cs i was thinking about how i can load remote images , 
IconManager is a complete package for loading and caching images , but its fields are not protected , means i could not extends this...

so i have made some alternations in Run() , plz accept these changes or if you have better idea ,do implement.

`IEnumerator Run()
	{
		_started = true;

		LoadItem item = null;
		while (true)
		{
			if (_items.Count > 0)
			{
				item = _items[0];
				_items.RemoveAt(0);
			}
			else
				break;

			if (_pool.ContainsKey(item.url))
			{
				//Debug.Log("hit " + item.url);

				NTexture texture = (NTexture)_pool[item.url];
				texture.refCount++;

				if (item.onSuccess != null)
					item.onSuccess(texture);

				continue;
			}

            string url ;
            bool indernal;

            if (item.url.IndexOf("ui://") == 0)
            {
                url = _basePath + item.url + ".ab";
                indernal = true;
            }
            else
            {
                url = item.url;
                indernal = false;
            }

            WWW www = new WWW(url);
			yield return www;

			if (string.IsNullOrEmpty(www.error))
			{

                NTexture texture;

                if (indernal)
                {
                    AssetBundle bundle = www.assetBundle;
                    if (bundle == null)
                    {
                        Debug.LogWarning("Run Window->Build FairyGUI example Bundles first.");
                        if (item.onFail != null)
                            item.onFail(www.error);
                        continue;
                    }
#if UNITY_5
                    texture = new NTexture(bundle.LoadAllAssets<Texture2D>()[0]);
#else
				NTexture texture = new NTexture((Texture2D)bundle.mainAsset);
#endif

                    bundle.Unload(false);
                }
                else
                {
                    texture = new NTexture( www.texture);

                }
                

                texture.refCount++;
				
				_pool[item.url] = texture;

				if (item.onSuccess != null)
					item.onSuccess(texture);
			}
			else
			{
				if (item.onFail != null)
					item.onFail(www.error);
			}
		}

		_started = false;
	}
`

**Comment by fairygui** [comment]
IconManager is just an example for how to use custom loader. It is not part of FairyGUI SDK.

**Comment by aammfe** [comment]
0k thanx
