### ISSUE TITLE
Any possibility of using TextMeshPro with FairyGUI List ItemRenderer?

### ISSUE THREAD

**Issue by manofspirit** [fairygui/FairyGUI-unity#28]
TextMeshPro has so many advantages, crisp + rich text etc, Can you please add its support so we can use it with your list item renderers?

**Comment by fairygui** [comment]
What rich text support do you want and they are not supported yet?

**Comment by manofspirit** [comment]
for me TMPro's Crisp rendering on any resolution is what makes it a first choice.
RichText come later.

**Comment by fairygui** [comment]
FairyGUI has a strongly support for rich text. As for crisp text request, it is duplicated with issue 4, which I have already marked it as enhancement.

**Comment by fairygui** [comment]
crisp text feature is added, please check.

**Comment by manofspirit** [comment]
You are unbelievably fast.
Please make a forum here so more and more people start using FairyGUI
https://forum.unity3d.com/forums/assets-and-asset-store.32/

**Comment by fairygui** [comment]
https://forum.unity3d.com/threads/fairygui-crossplatform-ui-system.415949/
