### ISSUE TITLE
Scroll Events 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#29]
FairyGui ScrollView has just two events , onPullDownRelease , onPullUpRelease ,it seems no way to create Animations Like [this](https://raw.githubusercontent.com/grumoon/PullListView/master/image/PullListViewSample3.gif)

but if you have any idea it is more better...

I have tried listView in NGUI where i made detailed scroll Events , Please take a look on it so it could be implemented in fairyGui ..

`public class ScrollEvents : MonoBehaviour
{

    public UnityEvent OnPullDownStarted;
    public UnityEvent OnPullDowned;
    public UnityEvent OnPullDownStartEnding;
    public UnityEvent OnPullDownEnded;
    

    public UnityEvent OnPullUpStarted;
    public UnityEvent OnPullUped;
    public UnityEvent OnPullUpStartEnding;
    public UnityEvent OnPullUpEnd;

    public class scrollEvent : UnityEvent<float> { };

    public scrollEvent OnPullDownScroll;
    public scrollEvent OnPullUpScroll;

    [Range(0, 100)] public int pullDownStartThreshold = 50;
    [Range(0 ,250)] public int pullDownThreshold = 100;
    [Range(0, 100)] public int pullDownEndThreshold = 50;

    [Range(0, 100)] public int pullUpStartThreshold = 50;
    [Range(0, 250)] public int pullUpThreshold = 100;
    [Range(0, 100)] public int pullUpEndThreshold = 50;

    private UIScrollView scrollView;
    private UIPanel panel;

    private bool moving;
    private bool dragging;

    private bool pullDownStarted;
    private bool pullDowned;
    private bool pullDownStartEnding;

    private bool pullUpStarted;
    private bool pullUped;
    private bool pullUpStartEnding;

    void Awake()
    {

        panel = GetComponent<UIPanel>();
        scrollView = GetComponent<UIScrollView>();

        scrollView.onDragStarted += OnDragStarted;
        scrollView.onDragFinished += OnDragFinished;
        scrollView.onStoppedMoving += OnStopMoving;

        OnPullDownStarted = new UnityEvent();
        OnPullDowned = new UnityEvent();
        OnPullDownStartEnding = new UnityEvent();
        OnPullDownEnded = new UnityEvent();

        OnPullUpStarted = new UnityEvent();
        OnPullUped = new UnityEvent();
        OnPullUpStartEnding = new UnityEvent();
        OnPullUpEnd = new UnityEvent();

        
        OnPullDownScroll = new scrollEvent();
        OnPullUpScroll = new scrollEvent();
    }

    

    private void OnDragStarted()
    {
        dragging = moving = true;
    }

    private void OnDragFinished()
    {
        dragging = false;
    }

    private void OnStopMoving()
    {
        moving = false;
        resetAllStates();
    }

    private Vector3 GetScrollViewConstraint()
    {
        Bounds b = scrollView.bounds;
        return panel.CalculateConstrainOffset(b.min, b.max);
    }

   

    void Update()
    {
        if (moving)
        {
            Vector3 constraint = GetScrollViewConstraint();

            if (constraint.y == 0)
            {
                CheckAnyPendingEvents();
                return;
            } 

            if (constraint.y > 0)
            {
                if (constraint.y > pullDownStartThreshold && pullDownStarted || pullDowned)
                {

                    float scrollValue = (constraint.y - pullDownStartThreshold) / (pullDownThreshold - pullDownStartThreshold);
                    scrollValue = Mathf.Clamp01(scrollValue);

                    if (OnPullDownScroll != null) OnPullDownScroll.Invoke(scrollValue);
                }

                if (constraint.y > pullDownThreshold && pullDownStarted && pullDowned == false)
                {
                    if (OnPullDowned != null) OnPullDowned.Invoke();
                    pullDowned = true;
                }

                else if (constraint.y < pullDownThreshold && pullDowned && pullDownStartEnding == false)
                {
                    if (OnPullDownStartEnding != null) OnPullDownStartEnding.Invoke();
                    pullDownStartEnding = true;
                }

                else if (constraint.y > pullDownStartThreshold && pullDowned == false && pullDownStarted == false && dragging)
                {
                    if (OnPullDownStarted != null) OnPullDownStarted.Invoke();
                    pullDownStarted = true;
                }

                else if (constraint.y < pullDownEndThreshold && (pullDownStarted || pullDowned))
                {
                    if (OnPullDownEnded != null) OnPullDownEnded.Invoke();
                    resetAllStates();
                }
            }
            else if (constraint.y < 0)
            {
                if (constraint.y < -pullUpStartThreshold && pullUpStarted || pullUped)
                {
                    float scrollValue = (constraint.y - pullUpStartThreshold) / (pullUpThreshold - pullUpStartThreshold);
                    scrollValue = Mathf.Clamp01(Mathf.Abs(scrollValue));

                    if (OnPullUpScroll != null) OnPullUpScroll.Invoke(scrollValue);
                }

                if (constraint.y < -pullUpThreshold && pullUpStarted && pullUped == false)
                {
                    if (OnPullUped != null) OnPullUped.Invoke();
                    pullUped = true;
                }

                else if (constraint.y < -pullUpStartThreshold && dragging && pullUpStarted == false && pullUped == false)
                {
                    if (OnPullUpStarted != null) OnPullUpStarted.Invoke();
                    pullUpStarted = true;
                }

                else if (constraint.y > -pullUpThreshold && pullUped && pullUpStartEnding == false)
                {
                    if (OnPullUpStartEnding != null) OnPullUpStartEnding.Invoke();
                    pullUpStartEnding = true;
                }

                else if (constraint.y > -pullUpEndThreshold && (pullUpStarted || pullUped))
                {
                    if (OnPullUpEnd != null) OnPullUpEnd.Invoke();
                    resetAllStates();
                }
            }
        }
    }

    private void CheckAnyPendingEvents()
    {
        if (pullDowned || pullDownStartEnding || pullDownStarted)
        {
            if (OnPullDownEnded != null) OnPullDownEnded.Invoke();
            resetAllStates();
        } 

        if (pullUpStarted || pullUpStartEnding || pullUped)
        {
            if (OnPullUpEnd != null) OnPullUpEnd.Invoke();
            resetAllStates();
        }
    }

    private void resetAllStates()
    {
        pullUpStartEnding = pullDownStartEnding = pullDownStarted = pullDowned = pullUpStarted = pullUped = false;
    }

    void OnDestroy()
    {
        scrollView.onDragStarted -= OnDragStarted;
        scrollView.onDragFinished -= OnDragFinished;
        scrollView.onStoppedMoving -= OnStopMoving;

        OnPullDownStarted.RemoveAllListeners();
        OnPullDowned.RemoveAllListeners();
        OnPullDownStartEnding.RemoveAllListeners();
        OnPullDownEnded.RemoveAllListeners();

        OnPullUpStarted.RemoveAllListeners();
        OnPullUped.RemoveAllListeners();
        OnPullUpStartEnding.RemoveAllListeners();
        OnPullUpEnd.RemoveAllListeners();
        
        OnPullDownScroll.RemoveAllListeners();
        OnPullUpScroll.RemoveAllListeners();
    }

  
}
`

**Comment by fairygui** [comment]
Features implemented in Editor 3.1.5 + SDK 1.8.3. View Example 26 - PullToRefresh.
