### ISSUE TITLE
List View Pagination Item Snapping Problem  

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#3]
[Horizontal Pagination List](http://techpearls.com/ilih/) in this example
When width change it draw only items which can fit in , means no extra cutting item , but here things are not as same , [Fairy ui](https://we.tl/vBI2KrvL6n)

Feathers UI uses concept of pages so when you say 10 items in a page then UI always show 10 items even if UI is able to show 20, so if you can implement something like that in future (After fixing all current list related issues) that’d be great  [feathers Example](https://feathersui.com/examples/tile-list/)

**Comment by fairygui** [comment]
New feature introduced in 1.7.2, pls check.
