### ISSUE TITLE
Links underline problem

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#32]
How to remove [underline](http://prntscr.com/datzcz) form links in richtext..
it does not [appears](http://prntscr.com/dau0jn) in fairy Editor

**Comment by fairygui** [comment]
HtmlParseOptions.DefaultLinkUnderline = false (Global Settings)
or GRichTextField.richTextField.htmlParseOptions.linkUnderline = false

**Comment by fairygui** [comment]
Hi, If you have any question, please go to this thread.
https://forum.unity3d.com/threads/fairygui-crossplatform-ui-system.415949/

**Comment by aammfe** [comment]
Great :)
