### ISSUE TITLE
Help in Project Structure

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#43]
Hi! 
could not run even a simple color component.

steps 
1- Create new project in Fairy GUI editor.
2- New Component.
3- Color it , and check bgColor 
4- Export.

Edit "Basics" Scene , 
Select Package and component ,  

Run 

> Create test@test failed!
UnityEngine.Debug:LogError(Object)
FairyGUI.UIPanel:CreateUI_PlayMode() (at D:/FairyGUI-unity/Scripts/UI/UIPanel.cs:336)
FairyGUI.UIPanel:Start() (at D:/FairyGUI-unity/Scripts/UI/UIPanel.cs:128)

Please Help to resolve it.
Fairy Gui Editor, Unity Plugin both are Updated.

using unity 5.6

**Comment by fairygui** [comment]
Where did your put the files test.bytes / test@atlas0.png in?

**Comment by aammfe** [comment]
![image](https://cloud.githubusercontent.com/assets/11896817/25780605/55fde490-3343-11e7-8e75-7cd549377818.png)

this is my project structure 
i just put it in assert folder 



now place all Fairy editor Exports in Resources but it dont work

**Comment by fairygui** [comment]
You need to put these files into Resources folder or its subfolders. If you had moved the files, set UIPanel package and component property in inspector again.

**Comment by aammfe** [comment]
:-) Thanx

**Comment by aammfe** [comment]
/** This is an automatically generated class by FairyGUI. Please do not modify it. **/

So how to use auto-generated code ...?

**Comment by fairygui** [comment]
On the startup (After AddPackage and before CreateObject), just call XXBinder.BinAll();

After that, you can create ui object by XXComponent.CreateInstance()

**Comment by aammfe** [comment]
Images are not loading ......

in fairy Editor  
![image](https://cloud.githubusercontent.com/assets/11896817/25783304/71f4c7a6-3373-11e7-8c7b-288154671bbc.png)

but in unity
![image](https://cloud.githubusercontent.com/assets/11896817/25783311/93dffa84-3373-11e7-9b1e-0f3c7ee10890.png)
