### ISSUE TITLE
Images Loading 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#44]
Images are not loading

> FairyGUI: texture 'atlas0.png' not found in TileView

in Fairy Editor
![image](https://cloud.githubusercontent.com/assets/11896817/25783318/c945929c-3373-11e7-857d-bc9d012be50c.png)
 

but in unity 
![image](https://cloud.githubusercontent.com/assets/11896817/25783314/ad69c5f2-3373-11e7-8d3d-339169538fcb.png)

**Comment by fairygui** [comment]
![20170211181456](https://cloud.githubusercontent.com/assets/9907813/25786832/cefcf5ea-33cd-11e7-8f0e-848db0328ec4.png)
