### ISSUE TITLE
List View Selection

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#45]
Hi!

Is there any Event like OnItemSelect ,  Or OnItemsSelected

and other this is Selection does not retains After item go off the screen . and come back.

1- Select mail 1 item
![image](https://cloud.githubusercontent.com/assets/11896817/25793705/1e6686aa-33e7-11e7-9845-47556f611786.png)

2- Scroll and let item go off the Screen
![image](https://cloud.githubusercontent.com/assets/11896817/25793730/3fed1eba-33e7-11e7-92cd-b219106c8b10.png)

3-Scroll To Previous item and it is not selected
![image](https://cloud.githubusercontent.com/assets/11896817/25793755/622c8376-33e7-11e7-8452-efefc166d6db.png)

**Comment by fairygui** [comment]
1. onClickItem event. In virtual list, you can use ChildIndexToItemIndex to get the real index.
2. Selection is not saved in virtual list. Set item status in onRenderItem callback.
