### ISSUE TITLE
Adjust Item Size with respect to children 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#5]
Does "Association" work with child to parent property?

means i have item ItemRenderer it has two labels , title and description ,
description.autosize = height;
and title has constant height , 

now problem is how can i assign..?
ItemRenderer.height  = title.height + description.height;

can i achieve it using association?

**Comment by fairygui** [comment]
Yes. Click on the empty space of  the stage, you can see relations settings of the container on right panels. Check 'Emoji' example. The list item height is associated with the title height.

**Comment by aammfe** [comment]
how to achieve this ..?
using Association ?

ItemRenderer.height = title.height + description.height;

can we do any thing like this code? and where it should be done?
like a function in feathersItemRenderer layoutContent ..?

**Comment by fairygui** [comment]
In Editor:
Step 1: Click the empty space of stage, activate the props panel of the component.
Step 2: In relation panel, create a new relation to your 'description' child, then set relation type to 'Height-Height'.

![image](https://cloud.githubusercontent.com/assets/9907813/19833846/b0a7fc1e-9e83-11e6-9374-daef465bd578.png)

Use code:
itemRenderer.AddRelation(descriptionChild, RelationType.Height_Height);

**Comment by aammfe** [comment]
is there any way we can do it in code ..?
like ItemRenderer with 5 + Items , how we can manually position things in x , y

**Comment by fairygui** [comment]
SetXY?

**Comment by aammfe** [comment]
yep Set Xy in code , is any function that can help us ..?
like feathers layout()

**Comment by fairygui** [comment]
GList has its layout, what layout you want?

**Comment by aammfe** [comment]
What i want is some way to manually specify child control layouting x and y
so lets say i have an item with picture, name, edit and delete button, and i want to change delete button’s position or size or even visiblity using code.

**Comment by fairygui** [comment]
GObject.setXY GObject.setSize  GObject.visible?
Not like feathers, nearly anything can be done in editor by using FairyGUI. We almost do not use code to handle layouts. Try to put all things ready in the editor, and use relation system to link A's position/size to B's position/size, use controller system to change position/size/visibility in different pages, use transition system to make animation effects.
