### ISSUE TITLE
Bitmap Fonts

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#50]
Creation of Bitmap fonts takes took much time.
1- use [littera](http://kvazars.com/littera/) to create sprite.
2- use showbox to unpack this sprite.
3-then import , include and assign characters to every sprite.

if some thing wrong, u have to do all these steps again. 
Seriously this is too much manual work.

may be i have done some overhead but character assigning is too much work.

I have used Textmesh pro untiy , where u just have to assign font ,simple settings 
and ur font is ready.  

it would be much more convenient if Add font automation in editor.  
Thanx

**Comment by fairygui** [comment]
Import fnt file directly into Editor.

**Comment by aammfe** [comment]
i have tried to import in editor and .fnt file show empty in editor.

[font.zip](https://github.com/fairygui/FairyGUI-unity/files/1031178/font.zip)

**Comment by fairygui** [comment]
select text format. xml format is not supported.

**Comment by aammfe** [comment]
[font.zip](https://github.com/fairygui/FairyGUI-unity/files/1031587/font.zip)
it is not working either.

**Comment by fairygui** [comment]
Tested your files,  it seems it's working.
![20170526215451](https://cloud.githubusercontent.com/assets/9907813/26497429/1273d336-425e-11e7-91bf-b7bc88dc5103.png)

**Comment by aammfe** [comment]
beg my pardon, my bad
