### ISSUE TITLE
Stage Camera

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#56]
Hi!
i m working on an application where i have used both FairyGUI and UGUI. 
Problem is when ever i shift from Fairy GUI Scene to UGUI scene. Stage Camera also popup there and leads some unexpected results. 
Please take a look on it.

**Comment by fairygui** [comment]
What is 'unexpected results'? Maybe you need to change Stage Camera's culling mask from 'UI to other values.

**Comment by aammfe** [comment]
In other scene where i m using FindObjectOfType<Camera>() is picking Stage Camera , but it should pick Scene other Camera.
