### ISSUE TITLE
建议GComponent组件Dispose时需要调用持有的Controller的RemoveEventListeners

### ISSUE THREAD

**Issue by kiolygenius** [fairygui/FairyGUI-unity#57]
在Unity + tolua# 环境下，如果在lua中注册了controller的onChange事件，然后整个GComponent Dispose时，注册到onChange的函数不会释放，导致这个函数引用的对象都无法释放。

**Comment by fairygui** [comment]
好的，我改改

**Comment by fairygui** [comment]
已经改进了
