### ISSUE TITLE
xLua support

### ISSUE THREAD

**Issue by CodeMasterYi** [fairygui/FairyGUI-unity#58]
xLua support在FairyGUI的近期的roadmap里面吗？

**Comment by fairygui** [comment]
无论tolua、slua还是xlua，都是C# binding的方案。FairyGUI是使用C#写的，且没有引用到除了系统库、Unity库外的任何第三方库，所以不存在支不支持某某lua的说法。xlua和FairyGUI结合使用的例子可以百度“FairyGUI xlua”。

**Comment by CodeMasterYi** [comment]
谢谢解答~
