### ISSUE TITLE
Layouts in Editor

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#6]
how i can assign layouts in components in fairy ui editor ..?

**Comment by fairygui** [comment]
Request more information.

**Comment by aammfe** [comment]
1- create component in editor.
2- create two children label of it , 
3- now i want to arrange then horizontally or vertically (yep we have to associate them)
but there us no way , we can assign layout (vertically or horizontally or any any layout..

**Comment by fairygui** [comment]
List can do that.

**Comment by aammfe** [comment]
problem is only list can do , it .. not other component.

**Comment by fairygui** [comment]
You are right. Currently that's the solution. Maybe it's something I can work on in the future.

**Comment by aammfe** [comment]
Thanx

**Comment by aammfe** [comment]
Plz reopen this issue just for reminder in future update..

**Comment by fairygui** [comment]
Layout feature added to advance group.
