### ISSUE TITLE
Anchor presets

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#60]
It would be great to have anchor presets like unity.
for now if I make a component with color I have to create a component make a child image or graph and then assign size as parent.
(I know it might be not a good example or you could change background color of component  with out image etc)

I really miss unity anchor presets over here , 

![image](https://user-images.githubusercontent.com/11896817/37988467-6bc5fcaa-321a-11e8-90d6-4218ed11e98e.png)

**Comment by fairygui** [comment]
We use Relation System instead of Anchor system. In the properties panel, add a relation to 'Container', and then select Width-Width, Height-Height.
