### ISSUE TITLE
Fill all While Keeping asp ratio Image loader

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#61]
Please Add support for "Fit with Smaller Dimension" in Image Loader.

What it will do..?

for remote images we don't know if its width is greater then height or vise versa.
so its a bit risk to just use fit height or fit width. or you have to manually check for it.

it would be great to have such option

![image](https://user-images.githubusercontent.com/11896817/37990881-f8cf3de0-3220-11e8-9576-8fc736173c55.png)

it would be some thing like this 
![image](https://user-images.githubusercontent.com/11896817/37991553-f2893010-3222-11e8-91a7-6fc63104e665.png)

here I m setting aspect ratio manually and it will assume me that it will always fill parent.
but here it will automatically getting aspect ratio from image texture

**Comment by fairygui** [comment]
What's the difference with 'Keep aspect ratio'?

**Comment by aammfe** [comment]
sorry it should be called some thing like "Fill all While Keeping asp ratio"

just like Envelop parent in upper image.

what it will do , it will keep asp ratio but scale texture both horizontal and vertically till there is no space on both sizes. 

in this cause I m using keep asp Size. but there is extra space on sides.
![image](https://user-images.githubusercontent.com/11896817/38008701-97b4ba28-3269-11e8-84c0-5f9688d202a9.png)

**Comment by aammfe** [comment]
overflow on either side is expected.
this type of behavior can be useful while using remote images where we don't know the texture dimensions. it will assure that image area will be filled , and overflow can be masked.

**Comment by fairygui** [comment]
Got it. I will add this option.

**Comment by aammfe** [comment]
it would be bonus if you add support for mask overflow 👍

**Comment by fairygui** [comment]
Option added. Editor 3.6.1 and SDK 2.1.0。
