### ISSUE TITLE
Inconsistency In Unity Export 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#63]
I m making a component , overflow is clipped 
![image](https://user-images.githubusercontent.com/11896817/38076594-7ff0c120-334f-11e8-9e4a-1a1aaad3bbb4.png)

it has out line
![image](https://user-images.githubusercontent.com/11896817/38076550-60cae4d8-334f-11e8-81b0-f2ee9173e07e.png)

and an image
![image](https://user-images.githubusercontent.com/11896817/38076697-d6d0ac94-334f-11e8-8b6d-77be8c44098f.png)

this is fairy GUI Editor Play mode.
![image](https://user-images.githubusercontent.com/11896817/38076739-fa267dcc-334f-11e8-9c16-ff7f0baf3810.png)

this is unity play mode.
![image](https://user-images.githubusercontent.com/11896817/38076773-107926ce-3350-11e8-9ac6-e4975a6d3c93.png)

**Comment by fairygui** [comment]
Yes, it could happen when lines with border-size bigger than 1. Not able to fix it currently.
