### ISSUE TITLE
Label \n behavior 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#66]
How i can Enable this behavior in fairy gui ?
![image](https://user-images.githubusercontent.com/11896817/38501245-f1fd34c2-3c25-11e8-8421-8742c80e9c29.png)

currently its like this.
![image](https://user-images.githubusercontent.com/11896817/38501157-c05d6aa4-3c25-11e8-8865-f381b03c657a.png)

**Comment by fairygui** [comment]
Hit enter key.
