### ISSUE TITLE
Rich text problem

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#67]
Hello!!
In editor its working fine but in unity its creating issue.
![image](https://user-images.githubusercontent.com/11896817/38689251-8c3d1b68-3e94-11e8-984d-79968fc5413d.png)
![image](https://user-images.githubusercontent.com/11896817/38690738-479da7e4-3e98-11e8-99fd-f14226f3f0dc.png)

This is the text which is creating issue 
[text.txt](https://github.com/fairygui/FairyGUI-unity/files/1904108/text.txt)

**Comment by fairygui** [comment]
I don't get any useful information from the picture, can you clarify it?

**Comment by aammfe** [comment]
when I assign this text to "Rich text" on run time its create this issue .

**Comment by aammfe** [comment]
this is sample scene 
[Empty 2d.zip](https://github.com/fairygui/FairyGUI-unity/files/1908859/Empty.2d.zip)

**Comment by fairygui** [comment]
"Mesh.vertices is too large. A mesh may not have more than 65000 vertices."

Text is too large to display. Try to put it into several textfields.
