### ISSUE TITLE
Readme.md 中的问题

### ISSUE THREAD

**Issue by scris** [fairygui/FairyGUI-unity#68]
Readme.md中有这么一句话：

> FairyGUI UI编辑器 操作简单，使用习惯与Adobe系列软件保持一致，策划和美术设计师可以轻松上手。在编辑器即可组合各种复杂UI组件，以及为UI设计动画效果，无需编写任何代码。可一键导出到Unity、Cocos2d-x、Cry Egine, Havok Vision/Project Anarchy、白鹭、LayaAir、Haxe、Pixi、Flash、Starling等多个主流应用和游戏平台。

Cry Egine 有误，应作 Cry Engine

**Comment by fairygui** [comment]
谢谢。
