### ISSUE TITLE
Hide A Control And Group Size 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#69]
Hello!!
I have a vGroup with lots of controls in it . when I
control101.visible = false; 

vGroup does not decrease its size .. is there any other way to hide control which is usable in this case?

as a workaround I did
scaleY = 0;

but it did not work also.

**Comment by fairygui** [comment]
visible=false is enough for hiding the group. If you do want to change the size of the group, simply call group.height = 0;
