### ISSUE TITLE
List FlowLayout Problem

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#7]
1- create List
2-apply FlowLayout 
3-Created Items With Different Size(height and Width)

1 - overFlow on each other [Problem](http://prntscr.com/d0zlur)
2 -items Disappearing during scrolling as stated before.

**Comment by fairygui** [comment]
Are you using virtual list with flow layout? If that so, only the height of the first item in each row is used for layout calculation.

**Comment by aammfe** [comment]
Using height and width of first time in a row’d turn flow layout useless, what you should do is follow feature approach taking height and width of the biggest item in that row. If you could do something like that’ it b great.

**Comment by fairygui** [comment]
If it is a solid list, it's simple. For virtual list, it's too complicated. So if you need this feature, use a solid list instead.
