### ISSUE TITLE
Limit visible text length 

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#70]
Hello!!

1- How can I use Text length limit to limit the visible text ? 

I assign a string to a label, but some times text is too long that I have to limit it up manually before assigning. but its also not straight forward. I m using Html to showup in  Richtext   if I limit string some times it cutout a tag.

If there is no option Addition of it would be great !!!  

2- tried to use Max Height of label its overflowing text . how I can clip it .. ? // create an other component for it ?

3- Created an other component and make a richtext child of it.
associate component height with richtext height so component row as richtext and assign a max height to component. 
it also did not work, component don't obey the max height.

**Comment by fairygui** [comment]
Try add relation for component to the text(not text to the component). And then set max height for the component.
