### ISSUE TITLE
Failed to choose item when fast clicking in sliding List

### ISSUE THREAD

**Issue by tidus5** [fairygui/FairyGUI-unity#72]
When using a list,   if one of these overflow option enabled :
* bounds back
* snapping to item
* PageMode

It may cause a problem. Sliding a list,  then fast clicking at a item,  but it failed to choose the item.

-----------------

当设置了 边缘回弹，自动贴近元件，页面模式。那么在列表滑动后归位过程中，快速点击可能导致一直选不中目标

**Comment by xiaoguzhu** [comment]
取消贴近和页面模式。
