### ISSUE TITLE
Rich Text Editor

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#75]
Hello!!

Can Please add support for rich text Editor.

I would be Great to have a rich text editor like [wysiwyg](https://www.google.com.pk/search?q=wysiwyg+editor+html&oq=wysiwyg+editor+html&aqs=chrome..69i57j0l5.12483j0j7&sourceid=chrome&ie=UTF-8)

Thanx

**Comment by xiaoguzhu** [comment]
It's difficult to do that kind of editor. However, a UBB editor is provided In 3.8.0 version, please check.
