### ISSUE TITLE
Updating old project to new fairy gui

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#77]
Hello!!

I have an old project created in old version of fairy gui.

now I'm updating it to new fairy gui .

but issue is package is not being shown in **Select a UI component**.

after digging more. I found.

class : EditorToolSet
line number 101

`string[] ids = AssetDatabase.FindAssets("_fui t:textAsset");
			int cnt = ids.Length;
			for (int i = 0; i < cnt; i++)
			{
				string assetPath = AssetDatabase.GUIDToAssetPath(ids[i]);
				int pos = assetPath.LastIndexOf("_fui");
				if (pos == -1)
					continue;`

is expecting **_fui** in exported file name.

I have updated fairy gui editor to 3.9.3

![image](https://user-images.githubusercontent.com/11896817/44797560-eba3f580-abc8-11e8-8e1b-483b3a6f92ce.png)

when I create new project in fairy gui editor and export it. It is producing correct name and in untiy editor it is picking it up correctly, but for old project like mine its not.

seems like New Fairy gui editor is not exporting old projects correctly.

![image](https://user-images.githubusercontent.com/11896817/44797865-a6cc8e80-abc9-11e8-865c-05c86fa9c755.png)

**Comment by xiaoguzhu** [comment]
Open publish dialog->global settings, check or uncheck 'Use binary format'. Version 3.9.0 introduce this new binary format.

**Comment by aammfe** [comment]
Thanx :)
