### ISSUE TITLE
建议在GRoot里面添加一个HideAllWindows的方法

### ISSUE THREAD

**Issue by w1ng** [fairygui/FairyGUI-unity#78]
如题。目前有个需求，想要隐藏所有当前Window，在隐藏的时候想要调用到这些Window的Hide方法。
发现GRoot只有一个CloseAllWindows的方法，所以仿照CloseAllWindows的实现写了个HideAllWindows。不知道作者能否直接提供这个实现，方便后续更新库 :)

**Comment by xiaoguzhu** [comment]
CloseAllWindows就是隐藏所有窗口，不需要什么HideAllWindows。
