### ISSUE TITLE
Screen and Screen Navigation

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#8]
Right now i m developing Application Using Fairy UI , But most Major Problem here is absence of Screens and Screen Navigation ,  
every time i have to reinvent the wheel , 

if you add [Screen ](https://feathersui.com/api-reference/feathers/controls/Screen.html) and [Screen Navigation](https://feathersui.com/help/screen-navigator.html) System Like Feathers it would be Great..

**Comment by fairygui** [comment]
FairyGUI is firstly focused on game development. Component+Transition can do  the same things.
