### ISSUE TITLE
Cutscene Scenes not auto added to build

### ISSUE THREAD

**Issue by CrandellWS** [fairygui/FairyGUI-unity#85]
http://answers.unity.com/answers/244170/view.html
With the scene asset reference, you can use the AssetDatabase object to get path information, and manually add the scene data to the build settings list of scenes.

```
 public Object[] mySceneAssets;

 List<EditorBuilderSettingsScene> scenes = new List<EditorBuilderSettingsScene>();
 //have some sort of for loop to cycle through scenes...
 string pathToScene = AssetDatabase.GetAssetPath(mySceneAssets[i]);
 EditorBuildSettingsScene scene = new EditorBuildSettingsScene(pathToScene, true);
 scenes.Add(scene);
 //later on...
 EditorBuildSettings.scenes = scenes.ToArray();
```

**Comment by CrandellWS** [comment]
perhaps this might be better 
https://docs.unity3d.com/ScriptReference/EditorBuildSettings-scenes.html

**Comment by CrandellWS** [comment]
and a  third way

https://forum.unity.com/threads/how-to-add-scenes-in-build-with-script-with-editorbuildsettings-scenes.116210/

**Comment by CrandellWS** [comment]
https://forum.unity.com/threads/how-to-link-scenes-in-the-inspector.383140/

**Comment by xiaoguzhu** [comment]
Thanks, will check it later

**Comment by CrandellWS** [comment]
that simplifies some of it for the end user it does work but there is a lot of room for error...
