### ISSUE TITLE
tolua监听

### ISSUE THREAD

**Issue by EP-Toushirou** [fairygui/FairyGUI-unity#86]
新版后，已经没有发现泄漏的出现，但是ScrollPanel.onScroll.Add调用时有问题，self没有传回来

**Comment by xiaoguzhu** [comment]
self由tolua底层传递，查tolua。

**Comment by xiaoguzhu** [comment]
这些都是在tolua里处理的，要改也只能改tolua的代码了。

**Comment by wayaya19851103** [comment]
我们项目也遇到这个问题，本来想更新到最新版本，但是由于已经到了项目后期，所有回调里都是用self的，每个都去改一遍的话，要花很多时间，只能先搁置，不知道有什么好办法能在回调里也能用self
