### ISSUE TITLE
文本框输入限制问题

### ISSUE THREAD

**Issue by lai0yu** [fairygui/FairyGUI-unity#88]
Unity 版本 2017.4.3f1 基于.Net3.5 Mono2.0；
FairyGUI-Unity-SDK 版本 3.3
FairyGUI编辑器版本3.10.2

我使用Fairy的文本组件作为作为输入框使用，想要限制输入为正负浮点数，我查看到教程关于文本框的输入限制说明导向了微软官方关于.Net正则表达式的网址，所以我使用了基于C#的正则表达式--@"^(-?\d+)(.\d+)?$"）；但这并不能达到我想要的结果。我在Unity中用代码检验了该正则表达式是正确的，但是FairyGUI却没有给我想要的结果！

FairGUI中文本输入限制的测试

编辑器
![i5jqdh6cw cw z 9y7h vr](https://user-images.githubusercontent.com/33061113/53548634-f1c16180-3b6c-11e9-97a7-c47a3e81a107.png)

代码
![x g4uqcztcc q4 6jqx t2](https://user-images.githubusercontent.com/33061113/53548673-0ef63000-3b6d-11e9-96db-0e7808b67afb.png)

使用Unity Script检验正则表达式
![3qz 33 qro89 x rb l3](https://user-images.githubusercontent.com/33061113/53548699-26351d80-3b6d-11e9-8e3c-7982db6228f6.png)

请问这是我使用的问题还是FairyGUI的Bug，如果是我使用的问题，望告知使用文本限制的正确做法！

**Comment by xiaoguzhu** [comment]
输入限制是指对输入的每个字符进行检测，通不过的不允许输入。而不是对整体文本进行匹配。

**Comment by lai0yu** [comment]
看了下源码，好像是这样的，但是我建议对整体文本同样进行匹配。并允许通过控制器页面控制；这样的话就方便很多了。这个FairyGUI的确很不错，谢谢！
