### ISSUE TITLE
Unity Battery Daring Solution

### ISSUE THREAD

**Issue by aammfe** [fairygui/FairyGUI-unity#9]
Hi!
I was googling "How i can Reduce Battery Drain Problem in Unity for App".
i found this post , [post](https://forum.unity3d.com/threads/using-unity-for-a-gui-only-application.200300/#post-1358011)

i think it would be better to share with you. and if it is possible include in fairy ui.

Unity re-Render every thing in Every Frame , wither it is needed or not , including fairy-ui components.
there is a solution  just for fairy ui.

assume we are working on just app development  ,means no 3d model.

Render only when its need to render by using upper mentioned post.
RenderOnce()

and now how to detect it needs to render or not ?
it could be done , by detecting input (by mouse movment , touchCount ), SizeChanged , PositionChanged for fairy-UI Component.

there All things Would be Customized, if any one wants to make renderer on every frame , he can do.

if you have better approach Plz apply it.  

like render only needed components. 
like [Starling](http://forum.starling-framework.org/topic/heads-up-starling-2-changes)

**Comment by aammfe** [comment]
An Other Thing Might help you [video](https://www.youtube.com/watch?time_continue=978&v=KK2hWczq8ZY)

**Comment by fairygui** [comment]
Looks like a possible solution for reduce battery consumption.
However, I think it is not a common scenarios of developing a APP with almost all static content by using Unity.
If that so, we have better choice like HTML5, etc.
I think it is something big effort,  small payback.

**Comment by aammfe** [comment]
"paybak" i have visited lot of unity forum where people where talking about making app in unity.
here some benefits.

1- multi platform , unity is unbelievable in this respect .
2- c# , and c# is the major reason people more tends to make app rather then HTML , where JavaScript  is Kills enough for killing your inner developer.
3- asset store.

now some major problems , 
1- pkg size , (we cant do any thing regarding this)
2- battery draining problem.
3-and major is no UI, unity Own UI is not good enough (performance problem).
it has scroll problem , means no production ready list.

NGUI has potential but there is no list component and even author has no interest in NGUI , people have try to make , me too but in my case i could not fully make it , work , still in production.

i know you know all these things , but just to tell you how much potential unity have to make app.

**Comment by fairygui** [comment]
In these days, many fairygui users have made APP using fairygui-unity, usually with VR or AR capabilities, so I think it's a good choice right now. Of course, if it is an information APP, I always feel that using Unity is not a good choice.
