### ISSUE TITLE
unity2018使用2017可以吗

### ISSUE THREAD

**Issue by noxue** [fairygui/FairyGUI-unity#90]
如题

**Comment by xiaoguzhu** [comment]
所有Unity版本都支持。

**Comment by noxue** [comment]
> 所有Unity版本都支持。

我在fgui上添加了一个文本  导入到unity2018里面  其他的图片之类的都显示，text不显示 请问下是什么原因

**Comment by noxue** [comment]
找到原因了 text输入状态的话 ，内容会自动清空  就好像不存在一样，其实是存在的。
