### ISSUE TITLE
进度条

### ISSUE THREAD

**Issue by EP-Toushirou** [fairygui/FairyGUI-unity#95]
调用GProgressBar.TweenValue(xxx, 3)后 若没有Tween完再调用GProgressBar.value = xxx
并且是同一个值的话 不会赋值成功 而是保持原来的Tween效果

**Comment by a340523052** [comment]
肯定是这样的，你看GprogressBar里的赋值value那里就知道了,就是值不一样的时候才帮你杀掉，你要想赋值成功就自己kill吧
```csharp
	public double value
		{
			get
			{
				return _value;
			}
			set
			{
				if (_value != value)
				{
					GTween.Kill(this, TweenPropType.Progress, false);

					_value = value;
					Update(_value);
				}
			}
		}
```

**Comment by EP-Toushirou** [comment]
可以这样得啊
public double value
		{
			get
			{
				return _value;
			}
			set
			{
				GTweener tweener = GTween.GetTween(this, TweenPropType.Progress);
				if (tweener != null)
				{
					GTween.Kill(this, TweenPropType.Progress, false);

					_value = value;
					Update(_value);
				}
				else
				{
					if (_value != value)
					{
						_value = value;
						Update(_value);
					}
				}
			}
		}

**Comment by xiaoguzhu** [comment]
自己Kill就是了。大部分情况都不用tween的，没必要每次赋值value都查询tween一次。

**Comment by EP-Toushirou** [comment]
请问最新代码是已经解决这个问题了吗？

**Comment by xiaoguzhu** [comment]
参考我最后一个回答。

**Comment by EP-Toushirou** [comment]
自己kill不是不行  就是大家这样用的话不方便啊😂 pr提的那个不行吗 做个标记
