### ISSUE TITLE
组件扩展button控制器的问题

### ISSUE THREAD

**Issue by sishui** [fairygui/FairyGUI-unity#97]
建立一个组件，添加一个控制器，使用button模板
然后在代码里调用 component.RemoveController()
点击的时候会在 parent.ApplyController(this); 的parent 是null
我看了下 RemoveController 并没有把 https://github.com/fairygui/FairyGUI-unity/blob/adf49566f83bbe0c2f2212a46d8751fd7d1c3534/Assets/Scripts/UI/GButton.cs#L472
的引用 置空，理论上 GComboBox 等控件 也应该有这个问题

**Comment by xiaoguzhu** [comment]
答案就是不能remove。remove它做什么。

**Comment by sishui** [comment]
有时候某些通用组件 需要放在 List 里，List 里需要选中状态，就需要这个控制器，但这个组件在外面用的时候就不需要这个控制器（同样可以点击）
当然如果这个是设计就如此，我换个方式实现就好了
