### ISSUE TITLE
Image通过设置color来设置透明度无效

### ISSUE THREAD

**Issue by a340523052** [fairygui/FairyGUI-unity#98]
`public Color color
		{
			get
			{
				return graphics.color;
			}
			set
			{
				graphics.color = value;
				graphics.Tint();
			}
}`

代码里是这样的，在Tint的时候会判断_meshDirty，修改颜色时没有SetMeshDirty，导致直接赋值color设置颜色无效，应该在graphics.Tint();之前加一句 graphics.SetMeshDirty();

**Comment by xiaoguzhu** [comment]
Demo测试正常。着色无需重建Mesh。

**Comment by a340523052** [comment]
```csharp
void __clickItem(EventContext context)
{
	GButton item = (GButton)context.data;
	if (this.contentPane.GetChild("n11").asLoader.url == null)
	{
	      this.contentPane.GetChild("n11").asLoader.url = item.icon;
        }
	else
	{
	      this.contentPane.GetChild("n11").asLoader.color = new Color(1, 1, 1, 0.5f);
        }	
        this.contentPane.GetChild("n13").text = item.icon;
}
```
谷主你试一下把BagWindow.cs这里的__clickItem改成这样，然后在Example 02 - Bag这个场景点击某个背包的某个item两下，第一下应该是修改url图片，第二下是改变透明度成0.5，但是修改透明度这个是没有效果的，要在Image的 graphics.Tint() 之前加一个graphics.SetMeshDirty();才有用

**Comment by xiaoguzhu** [comment]
你说的是颜色。透明度直接设置对象的alpha值，不需要搞这些东西。

**Comment by a340523052** [comment]
哦哦，之前在UGUI的image习惯用color来改透明度了，没看到有个alpha
