### ISSUE TITLE
Transition 不可见时自动停止

### ISSUE THREAD

**Issue by yangchg** [fairygui/FairyGUI-unity#99]
编辑器中动效，有“容器组件不可见时自动停止”，发现实际不可用。

相关代码：
internal void OnOwnerRemovedFromStage()
{
    if ((_options & OPTION_AUTO_STOP_DISABLED) == 0)
        Stop((_options & OPTION_AUTO_STOP_AT_END) != 0 ? true : false, false);
}

是不是和组件销毁停止混淆了？

**Comment by xiaoguzhu** [comment]
没有。正常。
